### ISSUE TITLE
deflate doesn't work with firefox

### ISSUE THREAD

**Issue by miyagawa** [plack/Plack-Middleware-Deflater#1]
deflate response doesn't get decoded properly by LWP clients and Firefox.

**Comment by ap** [comment]
I introduced Deflater in the codebase at $work in 2011 and we haven’t encountered any such problems in that time.

Maybe newer Firefox versions work correctly and versions from before that still would have the problem? Or maybe it was fixed at some point during the extensive body filter changes from 0.09 onward, though I can’t identify any specific commit as a fix. Maybe the code that was added into the synopsis in 0.04 was a workaround for this? We never used anything like it, though – the middleware always just worked for us with a simple `enable 'Deflater';`.
