### ISSUE TITLE
conditionally enable deflater based on response content type is hard

### ISSUE THREAD

**Issue by clkao** [plack/Plack-Middleware-Deflater#2]
because we have to wait for the underlying response to determine content_type.

right now you have to do:
        enable 'Deflater';
        enable sub { my $app = shift;
                     sub { my $env = shift;
                           my $res = $app->($env);
                           # skip streamy response
                           return $res unless ref($res) eq 'ARRAY' && $res->[2];
                           my $h = Plack::Util::headers($res->[1]);
                           my $type = $h->get('Content-Type')
                               or return $res;
                           delete $env->{HTTP_ACCEPT_ENCODING}
                               unless $type =~ m|application/x-javascript| || $type =~ m|^text/|;
                           $res }
                 };

but this doesn't disable the middleware completely, the side-effect is that deflater still removes the content-length header and adds vary header for your image/png responses, which is probably not cache-friendly

**Comment by ap** [comment]
This was fixed by the addition of the `plack.skip-deflater` PSGI env key in the 0.12 release, a few years after this issue was filed.
